#!/bin/bash
                                                                                                                                                          
#  ad88888ba                                        88                          88888888ba                                                                  
# d8"     "8b                                       ""                          88      "8b                                                                 
# Y8,                                                                           88      ,8P                                                                 
# `Y8aaaaa,     ,adPPYba,  8b,dPPYba,  8b       d8  88   ,adPPYba,   ,adPPYba,  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,  
#   `"""""8b,  a8P_____88  88P'   "Y8  `8b     d8'  88  a8"     ""  a8P_____88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8  
#         `8b  8PP"""""""  88           `8b   d8'   88  8b          8PP"""""""  88    `8b    88       88  88       88  88       88  8PP"""""""  88          
# Y8a     a8P  "8b,   ,aa  88            `8b,d8'    88  "8a,   ,aa  "8b,   ,aa  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88          
#  "Y88888P"    `"Ybbd8"'  88              "8"      88   `"Ybbd8"'   `"Ybbd8"'  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88          



#------------------------------------------------------------------------------------
# Initialisation of globals.

set -o nounset
MYDIR=$( dirname "$(readlink -f "$0")" )
source "$MYDIR/variables.sh"
source "$MYDIR/utils.sh"
e=$(printf "\e") 
readonly CODE_S="$e[32m"
readonly CODE_E="$e[0m"

#------------------------------------------------------------------------------------
# showhelp - give some info about the service. SERVICENAME and IMAGENAME are provided by variables.sh.

function showhelp {
cat <<EOF >&2
NAME
   ${SERVICENAME}
       
SYNOPSIS
   ${CODE_S}${SERVICENAME} help${CODE_E}
      This help.
   
   ${CODE_S}${SERVICENAME} start${CODE_E}
      Start the vault.
   
   ${CODE_S}${SERVICENAME} init${CODE_E}
      Initialise the vault.
   
DESCRIPTION
   Hashicorp Vault. Built from ${IMAGENAME}.
   
EOF
}

#------------------------------------------------------------------------------------
# Run a command in the container.

function dockerrun {
   docker exec -i -t ${SERVICENAME} "$@"
   [ $? -eq 0 ] || die "${SERVICENAME} ${COMMAND} failed."
}

#------------------------------------------------------------------------------------
# Run a detached command in the container. 

# detached, can't remove.
function dockerrundaemon {
   docker run -d "-p" "8200:8200" "--restart=always" \
		--name="${SERVICENAME}" -h "${HOSTNAME}" "${DOCKEROPTS[@]}" "${IMAGENAME}"
   # "$@"
   [ $? -eq 0 ] || die "${SERVICENAME} start failed."
}

#------------------------------------------------------------------------------------
# Stop a detached command in the container. 

function dockerstopdaemon {
   docker stop ${SERVICENAME} >/dev/null
   docker rm ${SERVICENAME} >/dev/null
}

#------------------------------------------------------------------------------------
# The main function. We can add any commands we'd like here!

function main {
   if [ "$#" -eq 0 ]; then 
      die "servicerunner must have the install argument."
   fi

   COMMAND="${1}"

   case "$COMMAND" in 
   
          #--- standard (required) commands
   
         install)
            ;;
            
         obliterate)
            dockerstopdaemon
            ;;
                     
         uninstall)
            dockerstopdaemon
            ;;
                     
         backupstart)
            BACKUPPATH="$2"
            ;;
         
         backupend)
            BACKUPPATH="$2"
            ;;
         
         restore)
            RESTOREPATH="$2"
            ;;
         
         help)
            showhelp
            ;;
         
         enter)
            shift
            dockerrun /bin/bash "$@"
            ;;
         
         updatestart)
            ;;

         updateend)
            ;;
         
         selftest)
            ;;
            
         #--- custom commands

         start)
            dockerrundaemon 
            ;;

         init)
            dockerrun vault init
            ;;
            
         unseal)
            shift
            dockerrun vault unseal "$@"
            ;;
            
         auth)
            shift
            dockerrun vault auth "$@"
            ;;
            
         read)
            shift
            dockerrun vault read "$@"
            ;;
            
         write)
            shift
            dockerrun vault write "$@"
            ;;
            
         #--- unrecognised commands

         *)
            showhelp
            die "Unrecognised command ${CODE_S}${COMMAND}${CODE_E}"            
            ;;
   esac
}

#------------------------------------------------------------------------------------

main "$@"
